TimesheetApp/barcode/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, FloatField,SubmitField,TextAreaField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo
from flask_wtf.file import FileField, FileAllowed

class AssetForm(FlaskForm):
    asset_add = StringField('Assets', validators=[DataRequired()])
    submit = SubmitField('Add')

class VendorForm(FlaskForm):
    vendor_add = StringField('Vendor', validators=[DataRequired()])
    submit = SubmitField('Add')

class ItemForm(FlaskForm):
    item_add = StringField('Item', validators=[DataRequired()])
    submit = SubmitField('Add')

class ConditionForm(FlaskForm):
    condition_add = StringField('Condition', validators=[DataRequired()])
    submit = SubmitField('Add')

TimesheetApp/barcode/views.py
import datetime
import os
import time
import json
import pyzbar.pyzbar as pyzbar
import numpy as np
from PIL import Image
import re
import io
from io import BytesIO
import base64, json
import random
import qrcode
from flask import render_template,url_for,flash, redirect,request,jsonify,Blueprint,abort,session,send_file, make_response,current_app,send_from_directory
from flask_login import current_user,login_required
from TimesheetApp import db
from TimesheetApp.models import Asset_Add,Vendor_Add,Item_Add,Condition_Add,Project_Add,KeyGen_Add,BarcodePost,Message,User,Remainder_Barcode,History_Barcode,Remainder_Itemcondition
from TimesheetApp.barcode.forms import AssetForm,VendorForm, ItemForm,ConditionForm
from sqlalchemy import and_
###Mail Services#########
import uuid
from TimesheetApp.utilities.common import email


barcode=Blueprint('barcode',__name__)

user_barcode_data = {}
user_barcode_data_reader = {}
user_codedata={}
user_codedata_reader={}

#########Admin Dashboard##########
@barcode.route('/create_asset', methods=['GET', 'POST'])
@login_required
def create_asset():
    if session.get('is_author')!=True:
        abort(403)
    form = AssetForm()
    if form.validate_on_submit():
        form.asset_add.data=form.asset_add.data.lower()
        asset_init=Asset_Add.query.filter_by(asset_add=form.asset_add.data).first()
        if asset_init is not None:
            flash('Asset has already been added! Add new asset!','danger')
            return redirect(url_for('barcode.create_asset'))
        asset_create = Asset_Add(asset_add=form.asset_add.data)
        db.session.add(asset_create)
        db.session.commit()
        flash('Asset has been successfully created!','success')
        return redirect(url_for('barcode.view_asset'))
    return render_template('barcode/create_asset.html', form=form)

@barcode.route('/view_asset')
@login_required
def view_asset():
    if session.get('is_author')!=True:
        abort(403)
    post_data=Asset_Add.query.all()
    return render_template('barcode/view_asset.html',post_data=post_data)

@barcode.route('/<int:post_id>/delete_asset')
@login_required
def delete_asset(post_id):
    if session.get('is_author')!=True:
        abort(403)
    post_data= Asset_Add.query.get_or_404(post_id)
    db.session.delete(post_data)
    db.session.commit()
    flash('Asset has been deleted!','danger')
    return redirect(url_for('barcode.view_asset'))

@barcode.route('/create_vendor', methods=['GET', 'POST'])
@login_required
def create_vendor():
    if session.get('is_author')!=True:
        abort(403)
    form = VendorForm()
    if form.validate_on_submit():
        form.vendor_add.data=form.vendor_add.data.lower()
        vendor_init=Vendor_Add.query.filter_by(vendor_add=form.vendor_add.data).first()
        if vendor_init is not None:
            flash('Vendor has already been added! Add new vendor!','danger')
            return redirect(url_for('barcode.create_vendor'))
        vendor_create = Vendor_Add(vendor_add=form.vendor_add.data)
        db.session.add(vendor_create)
        db.session.commit()
        flash('Vendor has been successfully created!','success')
        return redirect(url_for('barcode.view_vendor'))
    return render_template('barcode/create_vendor.html', form=form)

@barcode.route('/view_vendor')
@login_required
def view_vendor():
    if session.get('is_author')!=True:
        abort(403)
    post_data=Vendor_Add.query.all()
    return render_template('barcode/view_vendor.html',post_data=post_data)

@barcode.route('/<int:post_id>/delete_vendor')
@login_required
def delete_vendor(post_id):
    if session.get('is_author')!=True:
        abort(403)
    post_data= Vendor_Add.query.get_or_404(post_id)
    db.session.delete(post_data)
    db.session.commit()
    flash('Vendor has been deleted!','danger')
    return redirect(url_for('barcode.view_vendor'))

@barcode.route('/create_itemname', methods=['GET', 'POST'])
@login_required
def create_itemname():
    if session.get('is_author')!=True:
        abort(403)
    form = ItemForm()
    if form.validate_on_submit():
        form.item_add.data=form.item_add.data.lower()
        item_init=Item_Add.query.filter_by(item_add=form.item_add.data).first()
        if item_init is not None:
            flash('Item has already been added! Add new item!','danger')
            return redirect(url_for('barcode.create_itemname'))
        item_create = Item_Add(item_add=form.item_add.data,
                               item_key_gen=int(0))
        db.session.add(item_create)
        db.session.commit()
        flash('Item has been successfully created!','success')
        return redirect(url_for('barcode.view_itemname'))
    return render_template('barcode/create_itemname.html', form=form)

@barcode.route('/view_itemname')
@login_required
def view_itemname():
    if session.get('is_author')!=True:
        abort(403)
    post_data=Item_Add.query.all()
    return render_template('barcode/view_itemname.html',post_data=post_data)

@barcode.route('/<int:post_id>/delete_itemname')
@login_required
def delete_itemname(post_id):
    if session.get('is_author')!=True:
        abort(403)
    post_data= Item_Add.query.get_or_404(post_id)
    db.session.delete(post_data)
    db.session.commit()
    flash('Item has been deleted!','danger')
    return redirect(url_for('barcode.view_itemname'))

@barcode.route('/create_condition', methods=['GET', 'POST'])
@login_required
def create_condition():
    if session.get('is_author')!=True:
        abort(403)
    form = ConditionForm()
    if form.validate_on_submit():
        form.condition_add.data=form.condition_add.data.lower()
        condition_init=Condition_Add.query.filter_by(condition_add=form.condition_add.data).first()
        if condition_init is not None:
            flash('Item condition has already been added! Add new condition!','danger')
            return redirect(url_for('barcode.create_condition'))
        condition_create = Condition_Add(condition_add=form.condition_add.data)
        db.session.add(condition_create)
        db.session.commit()
        flash('Item condition has been successfully created!','success')
        return redirect(url_for('barcode.view_condition'))
    return render_template('barcode/create_condition.html', form=form)

@barcode.route('/view_condition')
@login_required
def view_condition():
    if session.get('is_author')!=True:
        abort(403)
    post_data=Condition_Add.query.all()
    return render_template('barcode/view_condition.html',post_data=post_data)

@barcode.route('/<int:post_id>/delete_condition')
@login_required
def delete_condition(post_id):
    if session.get('is_author')!=True:
        abort(403)
    post_data= Condition_Add.query.get_or_404(post_id)
    db.session.delete(post_data)
    db.session.commit()
    flash('Item condition has been deleted!','danger')
    return redirect(url_for('barcode.view_condition'))

@barcode.route('/history_view_all_admin')
@login_required
def history_view_all_admin():
    if session.get('is_author')!=True:
        abort(403)
    user_all=User.query.order_by(User.username).all()
    page = request.args.get('page', 1, type=int)
    post_submit=BarcodePost.query.order_by(BarcodePost.date_created.desc())
    post_history=History_Barcode.query.order_by(History_Barcode.date.desc()).paginate(page=page, per_page=25)
    post_barcode=BarcodePost.query.order_by(BarcodePost.date_created.desc())
    project_all=Project_Add.query.filter(Project_Add.project_archieve=='default')
    post_history_count=History_Barcode.query.order_by(History_Barcode.date.desc())
    #####Random Color Generation#########
    count_h=0
    for post_init_h in post_history_count:
        count_h=count_h+1
    color_all=[]
    color_choice=['red','yellow','blue','green','pink','orange','brown','purple']
    for random_count in range(count_h):
        color_r=random.choice(color_choice)
        color_all.append(color_r)
        #r = lambda: random.randint(0,255)
        #color_r = '#{:02x}{:02x}{:02x}'.format(r(), r(), r())
    return render_template('/barcode/history_view_all_admin.html',post_data=post_submit,project_all=project_all,
                                                              color_all=color_all,user_all=user_all,
                                                              post_history=post_history,post_barcode=post_barcode)
##############Inventory Selection #####################################
@barcode.route('/view_inventory_history_all_selection_admin',methods=['POST','GET'])
@login_required
def view_inventory_history_all_selection_admin():
    if request.method=='POST':
        user_get=request.form.get('user_select')
        model_select=request.form.get('model_select')
        desp_select=request.form.get('desp_select')
        page = request.args.get('page', 1, type=int)
        if user_get!='':
            post_submit=History_Barcode.query.filter(History_Barcode.user_update==user_get)\
                                                .order_by(History_Barcode.date.desc()).paginate(page=page, per_page=25)
        elif model_select!='':
            post_submit=History_Barcode.query.filter(History_Barcode.update_location==model_select)\
                                                .order_by(History_Barcode.date.desc()).paginate(page=page, per_page=25)
        elif desp_select!='':
            post_submit=History_Barcode.query.filter(History_Barcode.update_serialnum==desp_select)\
                                                .order_by(History_Barcode.date.desc()).paginate(page=page, per_page=25)
        else:
            post_submit=History_Barcode.query.order_by(History_Barcode.date.desc()).paginate(page=page, per_page=25)
    if request.method=='GET':
        page = request.args.get('page', 1, type=int)
        post_submit=History_Barcode.query.order_by(History_Barcode.date.desc()).paginate(page=page, per_page=25)
    user_all=User.query.order_by(User.username).all()

TimesheetApp/templates/barcode/create_asset.html
{% extends "/admin/basic.html" %}
{% block content %}
              <header class="page-title-bar">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item active">
                      <a href="{{url_for('adminDash.dash_admin')}}">
                        <i class="breadcrumb-icon fa fa-angle-left mr-2"></i>Creat Asset</a>
                    </li>
                  </ol>
                </nav>
                <span><font size="6" >Create Asset</font></span>
              </header>
              <!-- /.page-title-bar -->
              <!-- .page-section -->
              <div class="page-section">
                <div class="d-xl-none">
                  <button class="btn btn-danger btn-floated" type="button" data-toggle="sidebar">
                    <i class="fa fa-th-list"></i>
                  </button>
                </div>
                <!-- .card -->
                <section id="base-style" class="card">
                  <!-- .card-body -->
                  <div class="card-body">
                    <!-- .form -->
                    <form  method="POST" action="#">
                    {{ form.hidden_tag() }}  <!-- .fieldset -->
                    <div class="form-group">
                      <label for="asset_add_tag">{{ form.asset_add.label }}</label>
                      {{ form.asset_add(class="form-control") }}
                      {% for error in form.asset_add.errors %}
                      <span style="color:red;">[{{error}}]</span>
                      {% endfor %}
                    </div>
                      <div class="form-actions">
                        <button class="btn btn-primary" type="submit">Submit</button>
                      </div>
                    </form>

                  </div>
        </div>
{% endblock %}

TimesheetApp/templates/barcode/view_asset.html
{% extends "/admin/basic.html" %}
{% block content %}
              <header class="page-title-bar">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item active">
                      <a href="{{url_for('barcode.create_asset')}}">
                        <i class="breadcrumb-icon fa fa-angle-left mr-2"></i>View Asset</a>
                    </li>
                  </ol>
                </nav>
                <span><font size="6">View Asset </font></span>
              </header>
              <!-- /.page-title-bar -->
              <!-- .page-section -->
              <div class="page-section">
                <div class="d-xl-none">
                  <button class="btn btn-danger btn-floated" type="button" data-toggle="sidebar">
                    <i class="fa fa-th-list"></i>
                  </button>
                </div>
                <!-- .card -->
                <section id="base-style" class="card">
                  <!-- .card-body -->
                  <div class="card-body">
                    <div class="lits-group list-group-flush">
                      <!-- .lits-group-item -->
                      <!-- .table-responsive -->
                                   <div class="table-responsive">
                                     <!-- .table -->
                                     <table class="table table-sm mb-0">
                                       <!-- thead -->
                                       <thead class="thead-">
                                         <tr>
                                           <th><font color="#0f1f94"> Assets</font></th>
                                           <th><font color="#0f1f94"> Delete</font></th>
                                         </tr>
                                       </thead>
                                       <!-- /thead -->
                                       <!-- tbody -->
                                       <tbody>
                                         <!-- tr -->
                                         <tr>
                                           {% for post_in in post_data %}
                                           <td> {{post_in.asset_add}} </td>
                                           <td>
                                               <button type="submit" class="far fa-trash-alt" data-toggle="modal" data-target="#del_modal{{post_in.id}}"></button>
                                           </td>
                                         </tr>
                                         <!-- /.modal-->
                                         <div class="modal modal-alert fade" id="del_modal{{post_in.id}}" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalAlertDangerLabel" aria-hidden="true">
                                          <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                              <div class="modal-header">
                                                <h5 class="modal-title">
                                                  <i class="fa fa-exclamation-triangle text-red mr-1"></i>Delete Asset Item</h5>
                                              </div>
                                              <div class="modal-body">
                                                <p> Are you sure you want to delete asset item? </p>
                                              </div>
                                              <div class="modal-footer">
                                                <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
                                                <form action="{{url_for('barcode.delete_asset',post_id=post_in.id)}}" method="">
                                                  <input class="btn btn-danger" type="submit" value="Delete">
                                                </form>
                                              </div>
                                            </div>
                                          </div>
                                         </div>
                                         <!-- /.modal -->
                                          {% endfor %}
                                     </tbody>
                                   </table>
                                 </div>

              <!-- .lits-group-item -->
                    </div>


                  </div>
        </div>
{% endblock %}

TimesheetApp/templates/barcode/view_condition.html
{% extends "/admin/basic.html" %}
{% block content %}
              <header class="page-title-bar">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item active">
                      <a href="{{url_for('barcode.create_condition')}}">
                        <i class="breadcrumb-icon fa fa-angle-left mr-2"></i>View Item Condition</a>
                    </li>
                  </ol>
                </nav>
                <span><font size="6">View Item Condition </font></span>
              </header>
              <!-- /.page-title-bar -->
              <!-- .page-section -->
              <div class="page-section">
                <div class="d-xl-none">
                  <button class="btn btn-danger btn-floated" type="button" data-toggle="sidebar">
                    <i class="fa fa-th-list"></i>
                  </button>
                </div>
                <!-- .card -->
                <section id="base-style" class="card">
                  <!-- .card-body -->
                  <div class="card-body">
                    <div class="lits-group list-group-flush">
                      <!-- .lits-group-item -->
                      <!-- .table-responsive -->
                                   <div class="table-responsive">
                                     <!-- .table -->
                                     <table class="table table-sm mb-0">
                                       <!-- thead -->
                                       <thead class="thead-">
                                         <tr>
                                           <th><font color="#0f1f94"> Condition</font></th>
                                           <th><font color="#0f1f94"> Delete</font></th>
                                         </tr>
                                       </thead>
                                       <!-- /thead -->
                                       <!-- tbody -->
                                       <tbody>
                                         <!-- tr -->
                                         <tr>
                                           {% for post_in in post_data %}
                                           <td> {{post_in.condition_add}} </td>
                                           <td>
                                               <button type="submit" class="far fa-trash-alt" data-toggle="modal" data-target="#del_modal{{post_in.id}}"></button>
                                           </td>
                                         </tr>
                                         <!-- /.modal-->
                                         <div class="modal modal-alert fade" id="del_modal{{post_in.id}}" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalAlertDangerLabel" aria-hidden="true">
                                          <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                              <div class="modal-header">
                                                <h5 class="modal-title">
                                                  <i class="fa fa-exclamation-triangle text-red mr-1"></i>Delete Item Condition</h5>
                                              </div>
                                              <div class="modal-body">
                                                <p> Are you sure you want to delete {{post_in.condition_add}} condition? </p>
                                              </div>
                                              <div class="modal-footer">
                                                <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
                                                <form action="{{url_for('barcode.delete_condition',post_id=post_in.id)}}" method="">
                                                  <input class="btn btn-danger" type="submit" value="Delete">
                                                </form>
                                              </div>
                                            </div>
                                          </div>
                                         </div>
                                         <!-- /.modal -->
                                          {% endfor %}
                                     </tbody>
                                   </table>
                                 </div>

              <!-- .lits-group-item -->
                    </div>


                  </div>
        </div>
{% endblock %}

TimesheetApp/templates/barcode/view_itemname.html
{% extends "/admin/basic.html" %}
{% block content %}
              <header class="page-title-bar">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item active">
                      <a href="{{url_for('barcode.create_itemname')}}">
                        <i class="breadcrumb-icon fa fa-angle-left mr-2"></i>View Items</a>
                    </li>
                  </ol>
                </nav>
                <span><font size="6">View Item </font></span>
              </header>
              <!-- /.page-title-bar -->
              <!-- .page-section -->
              <div class="page-section">
                <div class="d-xl-none">
                  <button class="btn btn-danger btn-floated" type="button" data-toggle="sidebar">
                    <i class="fa fa-th-list"></i>
                  </button>
                </div>
                <!-- .card -->
                <section id="base-style" class="card">
                  <!-- .card-body -->
                  <div class="card-body">
                    <div class="lits-group list-group-flush">
                      <!-- .lits-group-item -->
                      <!-- .table-responsive -->
                                   <div class="table-responsive">
                                     <!-- .table -->
                                     <table class="table table-sm mb-0">
                                       <!-- thead -->
                                       <thead class="thead-">
                                         <tr>
                                           <th><font color="#0f1f94"> Item</font></th>
                                           <th><font color="#0f1f94"> Delete</font></th>
                                         </tr>
                                       </thead>
                                       <!-- /thead -->
                                       <!-- tbody -->
                                       <tbody>
                                         <!-- tr -->
                                         <tr>
                                           {% for post_in in post_data %}
                                           <td> {{post_in.item_add}} </td>
                                           <td>
                                               <button type="submit" class="far fa-trash-alt" data-toggle="modal" data-target="#del_modal{{post_in.id}}"></button>
                                           </td>
                                         </tr>
                                         <!-- /.modal-->
                                         <div class="modal modal-alert fade" id="del_modal{{post_in.id}}" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalAlertDangerLabel" aria-hidden="true">
                                          <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                              <div class="modal-header">
                                                <h5 class="modal-title">
                                                  <i class="fa fa-exclamation-triangle text-red mr-1"></i>Delete Item </h5>
                                              </div>
                                              <div class="modal-body">
                                                <p> Are you sure you want to delete {{post_in.item_add}} item? </p>
                                              </div>
                                              <div class="modal-footer">
                                                <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
                                                <form action="{{url_for('barcode.delete_itemname',post_id=post_in.id)}}" method="">
                                                  <input class="btn btn-danger" type="submit" value="Delete">
                                                </form>
                                              </div>
                                            </div>
                                          </div>
                                         </div>
                                         <!-- /.modal -->
                                          {% endfor %}
                                     </tbody>
                                   </table>
                                 </div>

              <!-- .lits-group-item -->
                    </div>


                  </div>
        </div>
{% endblock %}

TimesheetApp/templates/barcode/view_vendor.html
{% extends "/admin/basic.html" %}
{% block content %}
              <header class="page-title-bar">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item active">
                      <a href="{{url_for('barcode.create_vendor')}}">
                        <i class="breadcrumb-icon fa fa-angle-left mr-2"></i>View Vendor</a>
                    </li>
                  </ol>
                </nav>
                <span><font size="6">View Vendor </font></span>
              </header>
              <!-- /.page-title-bar -->
              <!-- .page-section -->
              <div class="page-section">
                <div class="d-xl-none">
                  <button class="btn btn-danger btn-floated" type="button" data-toggle="sidebar">
                    <i class="fa fa-th-list"></i>
                  </button>
                </div>
                <!-- .card -->
                <section id="base-style" class="card">
                  <!-- .card-body -->
                  <div class="card-body">
                    <div class="lits-group list-group-flush">
                      <!-- .lits-group-item -->
                      <!-- .table-responsive -->
                                   <div class="table-responsive">
                                     <!-- .table -->
                                     <table class="table table-sm mb-0">
                                       <!-- thead -->
                                       <thead class="thead-">
                                         <tr>
                                           <th><font color="#0f1f94"> Vendor</font></th>
                                           <th><font color="#0f1f94"> Delete</font></th>
                                         </tr>
                                       </thead>
                                       <!-- /thead -->
                                       <!-- tbody -->
                                       <tbody>
                                         <!-- tr -->
                                         <tr>
                                           {% for post_in in post_data %}
                                           <td> {{post_in.vendor_add}} </td>
                                           <td>
                                               <button type="submit" class="far fa-trash-alt" data-toggle="modal" data-target="#del_modal{{post_in.id}}"></button>
                                           </td>
                                         </tr>
                                         <!-- /.modal-->
                                         <div class="modal modal-alert fade" id="del_modal{{post_in.id}}" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalAlertDangerLabel" aria-hidden="true">
                                          <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                              <div class="modal-header">
                                                <h5 class="modal-title">
                                                  <i class="fa fa-exclamation-triangle text-red mr-1"></i>Delete Vendor </h5>
                                              </div>
                                              <div class="modal-body">
                                                <p> Are you sure you want to delete {{post_in.vendor_add}} vendor? </p>
                                              </div>
                                              <div class="modal-footer">
                                                <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
                                                <form action="{{url_for('barcode.delete_vendor',post_id=post_in.id)}}" method="">
                                                  <input class="btn btn-danger" type="submit" value="Delete">
                                                </form>
                                              </div>
                                            </div>
                                          </div>
                                         </div>
                                         <!-- /.modal -->
                                          {% endfor %}
                                     </tbody>
                                   </table>
                                 </div>

              <!-- .lits-group-item -->
                    </div>


                  </div>
        </div>
{% endblock %}