TimesheetApp/users/views.py
#users/views.py
from datetime import datetime
import time
from flask import render_template, url_for, flash, redirect, request, Blueprint,session,abort
from flask_login import login_user, current_user, logout_user, login_required
from TimesheetApp import db
from werkzeug.security import generate_password_hash,check_password_hash
from TimesheetApp.models import User, Message
from TimesheetApp.users.forms import LoginForm, UpdateAccountForm,UpdateProfileForm,MessageForm,ForgotForm,PasswordResetForm
#from TimesheetApp.users.picture_handler import add_profile_pic
######Mail Services###########
import uuid
from TimesheetApp.utilities.common import email
######Mail Services##########

users = Blueprint('users', __name__)

################LAST SEEN########################
###################DECORATOR####################
@users.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen=datetime.utcnow()
        db.session.commit()

##############LOGIN USER#################################
@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    error=None
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if not user is None:
            if user.check_password(form.password.data) and user is not None:
                if user.user_status!='active' or user.email_confirmed!=True:
                    error="Unauthorized  Login: Check Email and Password"
                    return render_template('login.html', form=form,error=error)
                login_user(user,remember=form.remember_me.data)
                session['is_author']=user.is_author
                #After Verify the validity of username and password
                session.permanent = True
                next = request.args.get('next')
                if next == None or not next[0]=='/':
                    if session.get('is_author')!=False:
                        flash('You are successfully logged in', 'success')
                        next = url_for('adminDash.dash_admin')
                    else:
                        flash('You are successfully logged in', 'success')
                        next = url_for('employees.dashboard')
                return redirect(next)
            else:
                error="Unauthorized  Login: Check Email and Password"
                return render_template('login.html', form=form,error=error)
        else:
            error="Unauthorized  Login: Check Email and Password"
            return render_template('login.html', form=form,error=error)
    return render_template('login.html', form=form,error=error)

###############LOGOUT USER######################
@users.route("/logout")
def logout():
    logout_user()
    flash('You are now logged out', 'success')
    return redirect(url_for('users.login'))

###########Forget Password#######################
@users.route('/forgot', methods=['GET', 'POST'])
def forgot():
    error = None
    message = None
    form = ForgotForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user:
            code = str(uuid.uuid4())
            user.password_reset_code=code
            db.session.commit()
            # email the user
            body_html = render_template('mail/user/password_reset.html', user=user)
            body_text = render_template('mail/user/password_reset.txt', user=user)
            email(user.email, "Password reset request", body_html, body_text)

        message = "You will receive a password reset email if your email is in our system"
    return render_template('users/forgot.html', form=form, error=error, message=message)
################Forget Password##############
################Password Reset Form#########
@users.route('/password_reset/<username>/<code>', methods=['GET', 'POST'])
def password_reset(username, code):
    message = None
    form = PasswordResetForm()
    user = User.query.filter_by(username=username).first_or_404()
    if not user or code != user.password_reset_code:
        abort(404)
    if request.method == 'POST':
        if form.validate_on_submit():
            user.password_hash=generate_password_hash(form.password.data)
            user.password_reset_code=''
            db.session.commit()
            return redirect(url_for('users.password_reset_complete'))
    return render_template('users/password_reset.html',form=form,message=message,
                                                    username=username,code=code
                            )
################Password Reset Form###########
@users.route('/password_reset_complete')
def password_reset_complete():
    return render_template('users/password_change_confirmed.html')
###########Password Reset Form################

########User Registration Confirmation##########
######Confirmation email from users for the registration########
@users.route('/confirm/<username>/<code>', methods=['GET', 'POST'])
def confirm(username, code):
    message = None
    form = PasswordResetForm()
    user = User.query.filter_by(username=username).first_or_404()
    if not user or code != user.confirmation_code:
        abort(404)
    if request.method == 'POST':
        if form.validate_on_submit():
            user.password_hash=generate_password_hash(form.password.data)
            user.email=user.confirmation_email
            user.email_confirmed=True
            user.confirmation_code=''
            db.session.commit()
            return redirect(url_for('users.register_confirm_complete'))
    return render_template('/users/confirm_register.html',message=message,form=form)

@users.route('/register_confirm_complete')
def register_confirm_complete():
    return render_template('users/register_confirm_complete.html')
########User Registration Confirmation##########

##########UPDATE USER PROFILE#################
@users.route("/profile_selection", methods=['GET', 'POST'])
@login_required
def profile_selection():
    import datetime
    form = UpdateProfileForm(request.form)
    error=None
    #if form.validate_on_submit():
    if request.method=='POST':
        current_user.firstname = form.firstname.data
        current_user.lastname = form.lastname.data
        current_user.position = form.position.data
        DOB_str=request.form.get('profile_DOB')
        if DOB_str=='' or form.firstname.data=='' or form.lastname.data=='':
            flash('Please Select Correct Format','danger')
            return redirect(url_for('users.profile_selection'))
        #DOB_user = datetime.datetime.strptime(DOB_str,'%Y-%m-%d')
        DOB_user = datetime.datetime.strptime(DOB_str,'%d/%m/%Y')
        ############UPDATING PROFILE OF USER ##################
        profile_update_user = User.query.filter_by(username=current_user.username).first()
        profile_update_user.firstname=form.firstname.data
        profile_update_user.lastname=form.lastname.data
        profile_update_user.position=form.position.data
        profile_update_user.birthday=DOB_user
        db.session.commit()
        flash('User profile has been successfully updated','success')
        return redirect(url_for('employees.dashboard'))
    if request.method == 'GET':
        form.firstname.data = current_user.firstname
        form.lastname.data = current_user.lastname
        form.position.data = current_user.position

    return render_template('/users/profile.html', form=form,error=error)

#######CHANGE PASSWORD #################
@users.route("/account_setting", methods=['GET','POST'])
@login_required
def account_setting():
    form = UpdateAccountForm()
    error=None
    if request.method=='POST':
        if form.validate_on_submit():
            user_dash = User.query.filter_by(username=current_user.username).first()
            user_dash.password_hash=generate_password_hash(form.password.data)
            db.session.commit()
            flash('Password has been changed successfully changed','success')
            return redirect(url_for('users.account_setting'))
    return render_template('/users/account.html',form=form,error=error)

##############MESSAGE SENDING #########################
@users.route('/send_message/<recipient>', methods=['GET', 'POST'])
@login_required
def send_message(recipient):
    user = User.query.filter_by(username=recipient).first_or_404()
    form = MessageForm()
    if form.validate_on_submit():
        msg = Message(author=current_user, recipient=user,
                      body_message=form.message.data)
        db.session.add(msg)
        #user.add_notification('unread_message_count', user.new_messages())
        db.session.commit()
        flash('Your message has been sent.')
        return "Thank you for sending message"
        #return redirect(url_for('main.user', username=recipient))
    return render_template('/users/send_message.html', title=('Send Message'),
                           form=form, recipient=recipient)

@users.route('/read_message')
@login_required
def read_messages():
    message=current_user.messages_received.order_by(Message.date.desc())
    return redirect(url_for('adminDash.dash_admin'))

@users.route('/dash_home')
@login_required
def dash_home():
    if session.get('is_author')!=False:
        return redirect(url_for('adminDash.dash_admin'))
    else:
        return redirect(url_for('employees.dashboard'))

TimesheetApp/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- End Required meta tags -->
    <!-- Begin SEO tag -->
    <title> Homepage. </title>
    <meta property="og:title" content="Sign In">
    <meta property="og:locale" content="en_US">
    <link rel="canonical" href="http://uselooper.com">
    <meta property="og:url" content="http://uselooper.com">
    <!-- End SEO tag -->
    <!-- Favicons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/profile_pics/tradepeer_new_logo.png">
    <link rel="shortcut icon" href="/static/profile_pics/tradepeer_new_logo.png">
    <meta name="theme-color" content="#3063A0">
    <!-- BEGIN BASE STYLES -->
    <link rel="stylesheet" href="/static/assets/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/assets/vendor/fontawesome/css/fontawesome.all.css">
    <!-- END BASE STYLES -->
    <!-- BEGIN THEME STYLES -->
    <link rel="stylesheet" href="/static/assets/stylesheets/main.min.css">
    <link rel="stylesheet" href="/static/assets/stylesheets/custom.css">
    <!-- END THEME STYLES -->
  </head>
  <body>

   <!-- .auth -->
    <main class="auth auth-floated">

      <!-- form -->
      <div class="auth-form">
        <div class="mb-4">
          <div class="mb-3">
            <br>
            <br>
            <img class="rounded" src="/static/profile_pics/tradepeer_new_logo.png" alt="" height="72"> </div>
        </div>
        <br>
        <br>
        <br>
        <br>
        <h6 class="display-4" align="center"><font color="#0076a8">Portal</font></h6>
        {% if current_user.is_authenticated %}
        <div class="form-group text-center">
          <form class="" action="{{url_for('users.logout')}}" method="">
            <button class="btn btn-lg btn-info btn-block" type="submit">Sign Out</button>
            </form>
            <br>
            <form class="" action="{{url_for('users.dash_home')}}" method="">
              <button class="btn btn-lg btn-primary btn-block" type="submit">Home</button>
              </form>
        </div>
        {% else %}
        <div class="form-group text-center">
          <form class="" action="{{url_for('users.login')}}" method="">
            <button class="btn btn-lg btn-info btn-block" type="submit">Sign In</button>
            </form>
        </div>
       {% endif %}
     </div>
      <!-- /.auth-form -->
      <!-- .auth-announcement -->
      <section id="announcement" class="auth-announcement");">
        <div class="announcement-body">
          <br>
          <br>
          <br>
          <br>
          <h6 class="display-4" align="center">Timesheets</h6>
          <h6 class="display-4" align="center">Portal</h6>
        </div>
      </section>
      <!-- /.auth-announcement -->

    </main>
    <!-- /.auth -->
    <!-- BEGIN PLUGINS JS -->
    <!-- END PLUGINS JS -->
  </body>
</html>

TimesheetApp/templates/login.html
<!DOCTYPE html>
<html lang="en">

  </head>
  <body>

   <!-- .auth -->
    <main class="auth auth-floated">

      <!-- form -->
      <form class="auth-form" method="POST" action="">
        {% include 'includes/_messages.html' %}
        <div class="mb-4">
          <div class="mb-3">
              <img class="rounded" src="/static/profile_pics/com_logo.png" alt="" height="72"> </div>
          <h1 class="h3"> Sign In </h1>
        </div>
        {# This hidden_tag is a CSRF security feature. #}
        {{ form.hidden_tag() }}
        <!-- .form-group -->
        <div class="form-group mb-4">
          <label class="d-block text-left">{{ form.email.label }}</label>
          {{ form.email(class="form-control form-control-lg") }}
          {% for error in form.email.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
        </div>
        <div class="form-group mb-4">
          <label class="d-block text-left">{{ form.password.label }}</label>
          {{ form.password(class="form-control form-control-lg") }}
          {% for error in form.password.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
        </div>
        <!-- /.form-group -->
        <!-- .form-group -->
        <div class="form-group mb-4">
          <button class="btn btn-lg btn-info btn-block" type="submit">Sign In</button>
        </div>
        <!-- /.form-group -->
        <!-- .form-group -->
        <div class="form-group text-center">
          <div class="custom-control custom-control-inline custom-checkbox">
            <p>{{form.remember_me()}} {{form.remember_me.label}}</p>
          </div>
        </div>
        <!-- /.form-group -->
        <!-- recovery links -->
        <p class="py-3">
          <a href="{{url_for('users.forgot')}}" class="link">Forgot Password?</a>
        </p>
        <!-- /recovery links -->
        </p>
      </form>
      <!-- /.auth-form -->
      <!-- .auth-announcement -->
  </body>
</html>