TimesheetApp/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField,SubmitField,TextAreaField
from wtforms.validators import ValidationError, DataRequired,Email,EqualTo,Length
from flask_wtf.file import FileField, FileAllowed

from flask_login import current_user
from TimesheetApp.models import User

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me=BooleanField('Keep me sign in')
    submit = SubmitField('Log In')

class UpdateProfileForm(FlaskForm):
    firstname = StringField('First name', validators=[DataRequired()])
    lastname = StringField('Last name', validators=[DataRequired()])
    position = StringField('Position', validators=[DataRequired()])
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Update Profile')

class UpdateAccountForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired(), EqualTo('pass_confirm', message='Passwords Must Match!')])
    pass_confirm = PasswordField('Confirm password', validators=[DataRequired()])
    submit = SubmitField('Update Password')

class MessageForm(FlaskForm):
    message = TextAreaField(('Message'), validators=[DataRequired(), Length(min=1, max=140)])
    submit = SubmitField(('Submit'))

class ForgotForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])

class PasswordResetForm(FlaskForm):
        password = PasswordField('Password', validators=[DataRequired(), EqualTo('pass_confirm', message='Passwords Must Match!')])
        pass_confirm = PasswordField('Confirm password', validators=[DataRequired()])

TimesheetApp/employees/views.py
import datetime
import os
import time
import random
from flask import render_template,url_for,flash, redirect,request,\
                    Blueprint,abort,session,send_file,current_app
from flask_login import current_user,login_required
from io import BytesIO
from werkzeug.utils import secure_filename
#from TimesheetApp import db,uploaded_images
from TimesheetApp import db
from TimesheetApp.models import User,TimeSheetPost,LeavePost,InvoicePost,\
                                        Project_Add,Task_Add,Invoice_Add,Task_Schedule,Message,Public_Holiday,\
                                        Allowance_Add,BarcodePost,Remainder_Barcode,Remainder_Itemcondition,\
                                        EnquiryPost
from TimesheetApp.employees.forms import Project_UserForm
from extensions import uploaded_images
from sqlalchemy import and_
###Mail Services#########
import uuid
from TimesheetApp.utilities.common import email

ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg', 'gif'])

employees = Blueprint('employees',__name__)

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

#####DASHBOARD##############
@employees.route('/dashboard')
@login_required
def dashboard():
    today_date=datetime.date.today()
    if current_user.birthday==None:
        message_card=''
    else:
        if(today_date.strftime('%m')==current_user.birthday.strftime('%m')) and (today_date.strftime('%d')==current_user.birthday.strftime('%d')):
            message_card='Happy Birthday !'
        else:
            message_card=''
    ##########Qrcode Notification to Users#########
    post_rem=Remainder_Barcode.query.order_by(Remainder_Barcode.date.asc())
    for post_in in post_rem:
        post_qrcode=BarcodePost.query.get(post_in.remainder_id)
        if post_qrcode !=None:
            requested_user=User.query.filter_by(username=post_in.remainder_user).first()
            if post_in.remainder_status=='approve' and requested_user==current_user and today_date >=post_in.remainder_date.date():
                user_message_ap='Hi {}! Have you received the {} with serial number {}.Report the condition'.format(current_user.firstname,
                                                                                                                    post_qrcode.item_add,
                                                                                                                    post_qrcode.item_serial_num)
                user_status_ap='unread'
                user_flag_ap=''
                user_title_ap='Report the condition of {}'.format(post_qrcode.item_serial_num)
                msg = Message(author=current_user, recipient=current_user,
                                body_message=user_message_ap,
                                body_title=user_title_ap,
                                body_flag=user_flag_ap,
                                body_trans='inventory_request_ack',
                                body_date=post_in.remainder_date,
                                body_id=post_qrcode.id,
                                body_sheet='default',
                                body_status=user_status_ap)
                db.session.add(msg)
                db.session.commit()
                ######send email to user for verification###########
                rem_post_email=Remainder_Barcode.query.filter(and_(Remainder_Barcode.remainder_id==post_qrcode.id,\
                                                                                Remainder_Barcode.remainder_date==post_in.remainder_date)).first()
                message_email='Have you received the {} with serial number {}.Report the condition'.format(post_qrcode.item_add,\
                                                                                                            post_qrcode.item_serial_num)
                body_html=render_template('mail/user/inventory_report_reminder.html',user=current_user,message_email=message_email,
                                                                                        post_rem_id=rem_post_email.id,post_id=post_qrcode.id)
                body_text=render_template('mail/user/inventory_report_reminder.txt',user=current_user,message_email=message_email,
                                                                                    post_rem_id=rem_post_email.id,post_id=post_qrcode.id)
                body_title='Report the condition of {}'.format(post_qrcode.item_serial_num)
                email(current_user.email,body_title,body_html,body_text)
                ######send email to user for verification###########
    #########DASHBOARD NOTIFICATION################
    page = request.args.get('page', 1, type=int)
    message_post=current_user.messages_received.order_by(Message.date.desc()).paginate(page=page, per_page=15)
    ################################################
    return render_template('users/dash.html',message_card=message_card,message_post=message_post)
########TIMESHEETS OF EMPLOYEES##############
@employees.route('/clockinout')
@login_required
def clockinout():
    project_all=Project_Add.query.filter(Project_Add.project_archieve=='default')
    task_all=Task_Add.query.all()
    return render_template('users/clockinout.html',task_all=task_all,project_all=project_all)

@employees.route('/clockinout_selection',methods=['GET','POST'])
@login_required
def clockinout_selection():
    if request.method=='POST':
        OverTime_15=0
        OverTime_25=0
        OverTime_2=0
        NormalTime=0
        Launch_Break=0
        hour_day=0
        ##Reading Arguments from Users
        day_clock_str=request.form.get('clockinout_fromD')
        clock_in_str=request.form.get('clockinout_fromT')
        clock_out_str=request.form.get('clockinout_toT')
        project=request.form.get('clockinout_project')
        task=request.form.get('clockinout_site')
        travel_choice=request.form.get('clockinout_travelch')
        meal_choice=request.form.get('meal_allowance')
        distance=request.form.get('clockinout_distance')
        location=request.form.get('clockinout_location')
        comment=request.form.get('clockinout_comment')

        user_id=current_user.id
        if (day_clock_str=='') or (project=='Choose...') or (task=='Choose...'):
            flash('Please Select Format Correctly','danger')
            return redirect(url_for('employees.clockinout'))
        ##Conversion from String to Format
        clock_in_strF= day_clock_str + clock_in_str
        clock_out_strF= day_clock_str + clock_out_str
        day_clock = datetime.datetime.strptime(day_clock_str,'%d/%m/%Y')
        clock_in = datetime.datetime.strptime(clock_in_strF,'%d/%m/%Y%H:%M')
        clock_out = datetime.datetime.strptime(clock_out_strF,'%d/%m/%Y%H:%M')
        ############Check same repetition and interval#################
        ###Hour Calculation of Employees
        time_dev=(clock_out-clock_in)/60
        hour_check,min_check= divmod(time_dev.seconds, 3600)
        hour_day=round((hour_check+float(min_check/60)),1)
        #######Check if Clockout time is not supported#############
        if(hour_day>24):
            flash('Please select properly Check Out Time','danger')
            return redirect(url_for('employees.clockinout'))
        #Default Initialization
        time_query=TimeSheetPost.query.filter(TimeSheetPost.day_clock==day_clock)\
                                            .filter(TimeSheetPost.user_id==current_user.id)
        hour_day_repeat=0
        Launch_Break_repeat=0
        NormalTime_repeat=0
        OverTime_15_repeat=0
        OverTime_25_repeat=0
        for time_init_query in time_query:
            if (clock_in>time_init_query.clock_in and clock_out<time_init_query.clock_out):
                flash('Checkin and Checkout time is overlapping','danger')
                return redirect(url_for('employees.clockinout'))
            if (clock_out>time_init_query.clock_in and clock_in<time_init_query.clock_out):
                flash('Checkin and Checkout time is overlapping','danger')
                return redirect(url_for('employees.clockinout'))
            time_dev2=(time_init_query.clock_out-time_init_query.clock_in)/60
            hour_check2,min_check2= divmod(time_dev2.seconds, 3600)
            hour_day2=round((hour_check2+float(min_check2/60)),1)
            hour_day_repeat=hour_day_repeat+hour_day2
            Launch_Break_repeat=Launch_Break_repeat+time_init_query.Launch_Break
            OverTime_15_repeat=OverTime_15_repeat+time_init_query.OverTime_15
            OverTime_25_repeat=OverTime_25_repeat+time_init_query.OverTime_25
            NormalTime_repeat=NormalTime_repeat+time_init_query.NormalTime
        hour_day_main=hour_day
        hour_day=hour_day_main+ hour_day_repeat
        #######MEAL ALLOWANCE####################################
        project_posts= Project_Add.query.filter(Project_Add.project_add==project)
        for allowance_init in project_posts:
            id_project=allowance_init.id
        project_query=Project_Add.query.get_or_404(id_project)
        if project_query.allowance_id=='default' and meal_choice=='no':
            meal_rate_day=float(0)
        elif project_query.allowance_id=='default' and meal_choice=='yes':
            meal_rate_day=float(0)
        elif project_query.allowance_id!='default' and meal_choice=='yes':
            allowance_list=project_query.allowance_id
            aw_all=allowance_list.split('-')
            meal_rate_day=0
            for aws_loop in aw_all:
                allowance_posts= Allowance_Add.query.filter(Allowance_Add.allowance_add==aws_loop)
                for aw_init in allowance_posts:
                    id_aws_ind=aw_init.id
                allowance_ind=Allowance_Add.query.get_or_404(id_aws_ind)
                if allowance_ind.allocate_unit=='hour':

TimesheetApp/templates/users/account.html
{% extends "/users/basic_dash.html" %}
{% block content %}
              <header class="page-title-bar">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item active">
                      <a href="{{url_for('employees.dashboard')}}">
                        <i class="breadcrumb-icon fa fa-angle-left mr-2"></i>{{current_user.firstname}} {{current_user.lastname}}</a>
                    </li>
                  </ol>
                </nav>
              </header>
              <!-- .page-title-bar -->
              <!-- /.page-title-bar -->
              <!-- .page-section -->
              <div class="page-section">
                <!-- page content goes here -->
                <div class="row">
                  <div class="col-lg-4">
                    <!-- .card -->
                    <div class="card card-fluid">
                      <h6 class="card-header"> Your Details </h6>
                      <!-- .nav -->
                      <nav class="nav nav-tabs flex-column">
                        <a href="{{url_for('users.profile_selection')}}" class="nav-link">Profile</a>
                        <a href="{{url_for('users.account_setting')}}" class="nav-link  active">Account</a>
                      </nav>
                      <!-- /.nav -->
                    </div>
                    <!-- /.card -->
                  </div>
                  <div class="col-lg-8">
                    <!-- .card -->
                    <div class="card card-fluid">
                      <h6 class="card-header">Account </h6>
                      <!-- .card-body -->
                      <div class="card-body">
                        <form method="POST" action="{{url_for('users.account_setting')}}">
                          {{ form.hidden_tag() }}
                          <div class="form-row">
                            <label for="passtag" class="col-md-3">{{ form.password.label }}</label>
                            <div class="col-md-9 mb-3">
                              {{ form.password(class="form-control") }}
                              {% for error in form.password.errors %}
                              <span style="color:red;">[{{error}}]</span>
                              {% endfor %}
                            </div>
                          </div>
                          <div class="form-row">
                            <label for="pass_confirm_tag" class="col-md-3">{{ form.pass_confirm.label }}</label>
                            <div class="col-md-9 mb-3">
                              {{ form.pass_confirm(class="form-control") }}
                              {% for error in form.pass_confirm.errors %}
                              <span style="color:red;">[{{error}}]</span>
                              {% endfor %}
                            </div>
                          </div>
                          <div class="form-actions">
                            <button type="submit" class="btn btn-primary ml-auto">{{form.submit.label}}</button>
                          </div>
                      </form>
                </div>
{% endblock %}

TimesheetApp/templates/users/clockinout.html
{% extends "/users/basic_input.html" %}
{% block content %}
              <header class="page-title-bar">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item active">
                      <a href="{{url_for('employees.dashboard')}}">
                        <i class="breadcrumb-icon fa fa-angle-left mr-2"></i>Clock-In Out</a>
                    </li>
                  </ol>
                </nav>
                <span><font size="6">Enter your hours</font></span>
              </header>
              <!-- /.page-title-bar -->
              <!-- .page-section -->
              <div class="page-section">
                <div class="d-xl-none">
                  <button class="btn btn-danger btn-floated" type="button" data-toggle="sidebar">
                    <i class="fa fa-th-list"></i>
                  </button>
                </div>
                <!-- .card -->
                <section id="base-style" class="card">
                  <!-- .card-body -->
                  <div class="card-body">
                    <!-- .form -->
                    <form  method="POST" action="{{url_for('employees.clockinout_selection')}}">
                      <!-- .fieldset -->
                      <fieldset>
                        <legend>Project Details</legend>
                        <div class="form-group">
                          <label for="clockinout_projecttag">Project Name</label>
                          <select class="form-control select2" name="clockinout_project" data-toggle="select2">
                           <option> Choose... </option>
                           {%for project_init in project_all%}
                           <option value="{{project_init.project_add}}"> {{project_init.project_add}} </option>
                           {%endfor%}
                         </select>
                        </div>
                        <div class="form-group">
                          <label for="clockinout_tasktag">Tasks</label>
                          <select class="form-control select2" name="clockinout_site" data-toggle="select2">
                            <option> Choose... </option>
                            {%for task_init in task_all%}
                            <option value="{{task_init}}"> {{task_init}} </option>
                            {%endfor%}
                         </select>
                        </div>
                        <div class="form-group">
                          <label class="control-label" for="flatpickr01">Select Day</label>
                          <input id="flatpickr01" type="text" class="form-control" name="clockinout_fromD" required="" value="">
                        </div>
                        <div class="form-group">
                          <label>Enter Clock In/Out Time</label>
                          <br>
                          <label class="control-label" for="flatpickr08">From </label>
                          <input id="flatpickr08" type="text" class="form-control" name="clockinout_fromT" value="">
                          <label class="control-label" for="flatpickr09">To</label>
                          <input id="flatpickr09" type="text" class="form-control" name="clockinout_toT" value="">
                        </div>

                        <div class="form-group">
                          <label>Meal Allowance?</label>
                          <div class="custom-control custom-radio">
                            <input type="radio" class="custom-control-input" name="meal_allowance" id="yestag" value="yes" >
                            <label class="custom-control-label" for="yestag">Yes</label>
                          </div>
                          <div class="custom-control custom-radio">
                            <input type="radio" class="custom-control-input" name="meal_allowance" id="notag" value="no" checked>
                            <label class="custom-control-label" for="notag">No</label>
                          </div>

                        </div>

                        <!-- /.form-group -->
                        <div class="form-group">
                          <label>Did you Travel?</label>
                          <div class="custom-control custom-radio">
                            <input type="radio" class="custom-control-input" name="clockinout_travelch" id="travel_yestag" value="yes" >
                            <label class="custom-control-label" for="travel_yestag">Yes</label>
                          </div>
                          <div class="custom-control custom-radio">
                            <input type="radio" class="custom-control-input" name="clockinout_travelch" id="travel_notag" value="no" checked>
                            <label class="custom-control-label" for="travel_notag">No</label>
                          </div>

                        </div>
                        <div class="form-group">
                          <label>If Yes?</label>
                          <div class="row">
                            <div class="col-md-6">
                              <label for="clockinout_distancetag">Travel Distance >50 kms</label>
                              <input type="number" class="form-control" id="clockinout_distancetag" name="clockinout_distance" value="">
                            </div>
                            <div class="col-md-6">
                              <label for="clockinout_locationtag">Where From?</label>
                              <input type="text" class="form-control" id="clockinout_locationtag" name="clockinout_location" value="">
                            </div>
                          </div>
                        </div>
                        <div class="form-group">
                          <label for="clockinout_commentag">Any Comment?</label>
                          <textarea class="form-control" id="clockinout_commentag" name="clockinout_comment" rows="2" cols="2"></textarea>
                        </div>
                        <!-- /.form-group -->
                      </fieldset>
                      <!-- /.fieldset -->
                      <div class="form-actions">
                        <button class="btn btn-primary" type="submit">Submit</button>
                      </div>
                    </form>

                  </div>
        </div>

         <script src="/static/assets/javascript/app.min.js"></script>
{% endblock %}

TimesheetApp/templates/users/create_project_user.html
{% extends "/users/basic_input.html" %}
{% block content %}
              <header class="page-title-bar">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item active">
                      <a href="{{url_for('employees.dashboard')}}">
                        <i class="breadcrumb-icon fa fa-angle-left mr-2"></i>Add Project</a>
                    </li>
                  </ol>
                </nav>
                <span><font size="6" >Create a project</font></span>
              </header>
              <!-- /.page-title-bar -->
              <!-- .page-section -->
              <div class="page-section">
                <div class="d-xl-none">
                  <button class="btn btn-danger btn-floated" type="button" data-toggle="sidebar">
                    <i class="fa fa-th-list"></i>
                  </button>
                </div>
                <!-- .card -->
                <section id="base-style" class="card">
                  <!-- .card-body -->
                  <div class="card-body">
                    <!-- .form -->
                    <form  method="POST" action="#">
                    {{ form.hidden_tag() }}  <!-- .fieldset -->
                    <div class="form-group">
                      <label for="project_add_tag">{{ form.project_add.label }}</label>
                      {{ form.project_add(class="form-control") }}
                      {% for error in form.project_add.errors %}
                      <span style="color:red;">[{{error}}]</span>
                      {% endfor %}
                    </div>
                    <div class="form-group">
                      <label for="job_add_tag">{{ form.job_add.label }}</label>
                      {{ form.job_add(class="form-control") }}
                      {% for error in form.job_add.errors %}
                      <span style="color:red;">[{{error}}]</span>
                      {% endfor %}
                    </div>
                    <div class="form-group">
                      <label for="project_add_tag">{{ form.allocate_project.label }}</label>
                      {{ form.allocate_project(class="form-control") }}
                      {% for error in form.allocate_project.errors %}
                      <span style="color:red;">[{{error}}]</span>
                      {% endfor %}
                    </div>
                    <div class="form-group">
                      <div>
                        <label for="myform">Select allowance</label>
                         <select id="myform" name='allowance_type' multiple class="form-control">
                           {%for allowance_init in allowance_all%}
                           <option> {{allowance_init.allowance_add}}</option>
                           {%endfor%}
                         </select>
                       </div>
                       <small class="text-muted">Select one or multiple only if allowance is allocated for a particular project </small>
                    </div>

                      <div class="form-actions">
                        <button class="btn btn-primary" type="submit">Submit</button>
                      </div>
                    </form>

                  </div>
        </div>
{% endblock %}

TimesheetApp/templates/users/dash.html
{% extends "/users/basic_message.html" %}
{% block content %}
<header class="page-title-bar">
  <p class="lead">
    <span class="font-weight-bold">Hi, {{ current_user.firstname}}</span>
    <br>
    <span class="font-weight-bold">{{ message_card}}</span>
    <span class="d-block text-muted">Welcome to Notice Board.</span>
    {% if current_user.last_seen %}
    <p>Last visited on:{{ moment(current_user.last_seen).format('LLL') }}</p>
    {% endif %}
  </p>
</header>

{% for post in message_post.items %}
              <!-- .page-section -->
              <div class="page-section">
                <!-- .card -->
              {% if post.body_status=='read' %}
                <section class="card text-white bg-secondary mb-3">
              {% elif post.body_trans=='timesheet' %}
                <section class="card text-white bg-warning mb-3">
              {% elif post.body_trans=='leave_request' %}
                <section class="card text-white bg-danger mb-3">
              {% elif post.body_trans=='invoice_request' %}
                <section class="card text-white bg-success mb-3">
              {%elif post.body_trans=='inventory_request'%}
              <section class="card text-white bg-warning mb-3">
              {%elif post.body_trans=='inventory_request_ack'%}
                <section class="card text-white bg-success mb-3">
              {%elif post.body_trans=='report_item_condition'%}
              <section class="card text-white bg-warning mb-3">
              {%else%}
                <section class="card text-white bg-secondary mb-3">
              {%endif%}
                  <!-- .list-group-messages -->
                  <div class="list-group list-group-messages list-group-flush list-group-bordered">
                    <!-- message item -->
                  {% if post.body_status=='unread' %}
                    <div class="list-group-item unread">
                  {%else%}
                    <div class="list-group-item read">
                  {%endif%}
                      <!-- message body -->
                      <div class="list-group-item-body pl-md-0">
                        <!-- grid row -->
                        <div class="row">
                          <!-- grid column -->
                          <div class="col">
                            <h4 class="list-group-item-title">
                              <a href="{{url_for('employees.message_read_user',username=current_user.username,mes_post_id=post.id)}}">{{post.body_title}}</a>
                            </h4>
                            <p class="list-group-item-text"> {{post.body_message}} </p>
                          </div>
                          <!-- /grid column -->
                          <!-- grid column -->
                          <div class="col-12 col-lg-2 text-lg-right">
                            <p class="list-group-item-text"> {{ moment(post.date).fromNow()}} </p>
                          </div>
                          <!-- /grid column -->
                        </div>
                        <!-- /grid row -->
                      </div>
                      <!-- /message body -->
                      <!-- message actions -->
                      <div class="list-group-item-figure">
                        <!-- .dropdown -->
                        <div class="dropdown">
                          <button class="btn btn-reset px-2" data-toggle="dropdown">
                            <i class="fa fa-ellipsis-v"></i>
                          </button>
                          <div class="dropdown-arrow"></div>
                          <!-- .dropdown-menu -->
                          <div class="dropdown-menu dropdown-menu-right">
                            <a href="{{url_for('employees.message_read_user',username=current_user.username,mes_post_id=post.id)}}" class="dropdown-item">Mark as read</a>
                            <a href="{{url_for('employees.message_unread_user',username=current_user.username,mes_post_id=post.id)}}" class="dropdown-item">Mark as unread</a>
                            <a href="{{url_for('employees.message_trash_user',username=current_user.username,mes_post_id=post.id)}}" class="dropdown-item">Trash</a>
                          </div>
                          <!-- /.dropdown-menu -->
                        </div>
                        <!-- /.dropdown -->
                      </div>
                      <!-- /message actions -->
                    </div>
                    <!-- /message item -->
                    <!-- message item -->
                  </div>
                  <!-- /.list-group-messages -->
                </section>
{% endfor %}

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center mt-4">

                        <li class="page-item disabled">
                          <a class="page-link"  tabindex="-1">
                            <i class="fa fa-lg fa-angle-left"></i>
                          </a>
                        </li>
            {% for page_num in message_post.iter_pages(left_edge=3, right_edge=3, left_current=3, right_current=3) %}
                     {% if page_num%}
                        <li class="page-item">
                          <a class="page-link" href="{{url_for('employees.dashboard',page=page_num)}}">{{page_num}}</a>
                        </li>
                      {%else%}
                        <li class="page-item disabled">
                          <a class="page-link" href="#" tabindex="-1">...</a>
                        </li>
                      {%endif%}
              {%endfor%}
                        <li class="page-item">
                          <a class="page-link">
                            <i class="fa fa-lg fa-angle-right"></i>
                          </a>
                        </li>

                      </ul>
</nav>
{% endblock %}